name: Addon build
run-name: Building addon
on: 
  workflow_dispatch:
    inputs:
      artifact_addon:
        description: 'Get artifacts'
        required: true
        default: false
        type: boolean
      artifact_test_room:
        description: 'Get test_room'
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Installing dependencies
        run: pacman -Syu --noconfirm git bash yasm python python-pip scons gcc diffutils make wget unzip tar mingw-w64 ffmpeg

      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Build Linux
        run: |
          scons -j4 target=template_debug platform=linux arch=x86_64 use_system=yes dev_build=yes
          scons -j4 target=template_debug platform=linux arch=x86_64 use_system=no dev_build=yes
          scons -j4 target=template_release platform=linux arch=x86_64 use_system=yes
          scons -j4 target=template_release platform=linux arch=x86_64 use_system=no recompile_ffmpeg=no


      - name: Build Windows
        run: |
          scons -j4 target=template_debug platform=windows arch=x86_64 dev_build=yes recompile_ffmpeg=yes
          scons -j4 target=template_release platform=windows arch=x86_64 recompile_ffmpeg=no


      - name: Copying libs
        run: |
          cp -r bin/* test_room/addons/gde_gozen/bin/
          cp LICENSE test_room/addons/gde_gozen/

      - name: Uploading addon build
        if: ${{ github.event.inputs.artifact_addon == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: Addon_GDE_GoZen
          path: test_room/addons/
          retention-days: 1

      - name: Uploading test room build
        if: ${{ github.event.inputs.artifact_test_room == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: test_room
          path: test_room/
          retention-days: 1
